#!/usr/bin/env bash
set -e

NAME=$1
REVISION=$4
REVISION=${REVISION:=master}

npm install -g component@1.1.0

echo "deploying revision ${REVISION} of repository ${NAME}"

CURRENT=`pwd`

echo "current directory ${CURRENT}"

git checkout ${REVISION} || true

VERSION=${RELEASE_TAG:=master}
LOCATION=${NAME}/${VERSION}
PREFIX=/${LOCATION}/

component build --out ${NAME} --name index --prefix ${PREFIX}

cd ${CURRENT}

node .deploy/components-uploader $CURRENT/${NAME} ${LOCATION}

echo "released ${REVISION} of ${NAME} as ${VERSION}"