#!/usr/bin/env bash

NAME=$1
REVISION=$4
REVISION=${REVISION:=master}

npm install -g component@1.1.0

echo "deploying revision ${REVISION} of repository ${NAME}"

CURRENT=`pwd`

git checkout ${REVISION}

VERSION=`date +%s`
LOCATION=${NAME}/${VERSION}
PREFIX=/${LOCATION}/

component build --out ${NAME} --name index --prefix ${PREFIX}

cd ${CURRENT}

node components-uploader $CURRENT/sources/${NAME} ${LOCATION}
node release-create ${NAME} ${VERSION} ${REVISION}

echo "released ${REVISION} of ${NAME} as ${VERSION}"